# Generated by Django 4.2.5 on 2023-09-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_entregable_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.estudiante'),
            preserve_default=False,
        ),
    ]
